# Generated by Django 4.0.4 on 2022-05-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EhospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=25)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=20)),
                ('Service', models.CharField(choices=[('DC', 'Dental Checkup'), ('FC', 'FullBody Checkup'), ('ENT', 'ENT Checkup'), ('HC', 'Heart Checkup')], max_length=20)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EhospitalApp.profile')),
            ],
        ),
    ]
