# Generated by Django 4.0.4 on 2022-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EhospitalApp', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Book_Date',
            field=models.DateField(auto_created=True, default='2000-01-01'),
        ),
    ]
