# Generated by Django 4.0.4 on 2022-05-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EhospitalApp', '0003_appointment_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EhospitalApp.master'),
            preserve_default=False,
        ),
    ]
